version: "3.7"

x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-extending_airflow:latest}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAG_DIR_LIST_INTERVAL: 1
    AIRFLOW__CORE__MIN_FILE_PROCESS_INTERVAL: 1
    AIRFLOW__SCHEDULER__PROCESSOR_POLL_INTERVAL: 1
    AIRFLOW__SCHEDULER__PARSING_PROCESSES: 1
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
  depends_on:
    postgres:
      condition: service_healthy
  networks:
      - etl-dashboard-network


services:

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - etl-dashboard-network
  
  superset:
    image: apache/superset:latest
    container_name: superset_webserver
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_ENV=production
      - SUPERSET_SECRET_KEY=dcc2fa1f0626330986d09ad29e12e748503bb900eb74ee56aa422010742e92cf
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://airflow:airflow@postgres:5432/superset\
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_FIRSTNAME=Superset
      - ADMIN_LASTNAME=Admin
      - ADMIN_EMAIL=admin@example.com
    command: >
      sh -c "superset db upgrade &&
            superset fab create-admin --username $$ADMIN_USERNAME --firstname $$ADMIN_FIRSTNAME --lastname $$ADMIN_LASTNAME --email $$ADMIN_EMAIL --password $$ADMIN_PASSWORD || true &&
            superset init &&
            superset run -h 0.0.0.0 -p 8088"

    volumes:
      - superset:/app/superset_home
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - etl-dashboard-network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler


  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

volumes:
    superset:
    postgres-db-volume:

networks:
  etl-dashboard-network:
    driver: bridge
